services:
  app:
    build: .
    command: npm start
    env_file:
      - .env
    tmpfs:
      - /tmp:size=512m
    ports:
      - "3100:3000"
    depends_on:
      - redis
      - mongo

  worker:
    build: .
    command: npm run worker
    env_file:
      - .env
    tmpfs:
      - /tmp:size=512m
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7-alpine

  mongo:
    image: mongo:7
    tmpfs:
      - /data/db:size=512m
